#! /usr/bin/env python

# Software License Agreement (BSD License)
#
# Copyright (c) 2013, Guilherme Franco
# All rights reserved.
#
import serial
import rospy
from nmea_msgs.msg import Sentence


def nmeaSentenceCallback(data):
    global GPS
    if data.sentence != "":
        print("Sending: " + data.sentence)
        if (data.sentence.split(",")[0] in protocols) or protocols[0] == "":
            pass
            GPS.writelines(data.sentence + "\n")
    # GPS.writelines("$GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,W*6A"+"\n")


if __name__ == '__main__':
    rospy.init_node('nmea_topic_virtual_serial_writer')

    nmea_sub = rospy.Subscriber("nmea_sentence", Sentence, nmeaSentenceCallback)

    serial_port = rospy.get_param('~port','/dev/ttyUSB0')
    serial_baud = rospy.get_param('~baud',4800)
    protocols = rospy.get_param('~protocols','$GPRMC').split(",")

    try:
        GPS = serial.Serial(port=serial_port, baudrate=serial_baud, rtscts=True, dsrdtr=True)
        rospy.spin()

    except rospy.ROSInterruptException:
        GPS.close() #Close GPS serial port
