#! /usr/bin/env python

# Software License Agreement (BSD License)
#
# Copyright (c) 2013, Guilherme Franco
# All rights reserved.
#
import rospy
from nmea_msgs.msg import Sentence


def nmeaSentenceCallback(data):
    print(data.sentence)

if __name__ == '__main__':
    rospy.init_node('zodiac_autonomous_py_node')
    nmea_sub = rospy.Subscriber("nmea_sentence", Sentence, nmeaSentenceCallback)
    rospy.spin()
