#!/usr/bin/env python
# coding=utf-8

# Author : Maël LE GALLIC
# Date : 06/06/2018

import rospy
from std_msgs.msg import Float64
from geometry_msgs.msg import PoseStamped, Pose, Twist, Quaternion, TwistStamped
from math import floor
from nmea_msgs.msg import Sentence
import tf
from numpy import rad2deg


def quaternionToQuaternionMsg(quat):
    q = Quaternion()
    q.x = quat[0]
    q.y = quat[1]
    q.z = quat[2]
    q.w = quat[3]
    return q

def quaternionMsgToQuaternion(quat):
    return ( quat.x, quat.y, quat.z, quat.w )

def getYaw(pose):
    roll, pitch, yaw = tf.transformations.euler_from_quaternion(quaternionMsgToQuaternion(pose.pose.orientation))
    return yaw

def checksum(msg):
    return str(hex(reduce((lambda a,b : a^b), map(ord, msg))))[2:]

def secsToNmeaTime(secs):
    hours = floor(secs/3600)
    secs -= hours*3600
    hours = (hours/24. - floor(hours/24.))*24
    minutes = floor(secs/60)
    secs -= minutes*60
    return "{0:02}{1:02}{2:02}".format(int(hours), int(minutes), int(floor(secs)))

class FakeCompass:
    def __init__(self):
        rospy.Subscriber('boat_heading', Float64, self.cb_heading, queue_size=1000000)
        self.pub_nmea = rospy.Publisher('nmea_sentence', Sentence, queue_size=1000000)
        self.rate = rospy.Rate(rospy.get_param('~rate', 3))
        self.cur_heading = None

    def cb_heading(self, heading_msg):
        self.cur_heading = heading_msg

    def sendGPHDT(self):
        if self.cur_heading == None:
            return
        yaw = self.cur_heading.data
        msg_comp = "HCHDT," + str(yaw) + ",T"
        self.sendSentence(msg_comp)

    def sendSentence(self, msg):
        sentence = Sentence()
        sentence.header.stamp = rospy.Time.now()
        sentence.sentence = "$" + msg + "*" + checksum(msg)
        self.pub_nmea.publish(sentence)

    def run(self):
        while not rospy.is_shutdown():
            self.sendGPHDT()
            self.rate.sleep()

if __name__ == '__main__':
    rospy.init_node('fake_compass')
    FakeCompass().run()
